---
title: "Knapsack Problem"
output: html_notebook
---

```{r}
source('knapsack_functions.r')
source('analysis_functions.r')
```
#Varying the Mutation
```{r}

for(b in 1:6){
  if(b == 1){
    file_name = "knapsack_csv/knapPI_11_100_1000_2_900_3990_0.csv"
  }else if(b == 2){
    file_name = "knapsack_csv/knapPI_11_100_1000_84_25070_43824_0.csv"
  }else if(b == 3){
    file_name = "knapsack_csv/knapPI_11_100_1000_65_48518_46822_0.csv"
  }else if(b == 4){
    file_name = "knapsack_csv/knapPI_11_100_1000_40_23019_5808_0.csv"
  }else if(b == 5){
    file_name = "knapsack_csv/knapPI_11_100_1000_12_7719_8742_0.csv"
  }else if(b == 6){
    file_name = "knapsack_csv/knapPI_11_100_1000_97_46329_22872_0.csv"
  }
  mutation_test_results = varied_mutation_test(file_name, 0.8)
  csv_name <- paste0('mutation_test_results','_',b,'.csv') #Write output csv file name
  write.csv(mutation_test_results, file = csv_name) #Write csv file
  
}

```

#Varying the Crossover

```{r}
for(b in 1:6){
  if(b == 1){
    file_name = "knapsack_csv/knapPI_11_100_1000_2_900_3990_0.csv"
  }else if(b == 2){
    file_name = "knapsack_csv/knapPI_11_100_1000_84_25070_43824_0.csv"
  }else if(b == 3){
    file_name = "knapsack_csv/knapPI_11_100_1000_65_48518_46822_0.csv"
  }else if(b == 4){
    file_name = "knapsack_csv/knapPI_11_100_1000_40_23019_5808_0.csv"
  }else if(b == 5){
    file_name = "knapsack_csv/knapPI_11_100_1000_12_7719_8742_0.csv"
  }else if(b == 6){
    file_name = "knapsack_csv/knapPI_11_100_1000_97_46329_22872_0.csv"
  }
  crossover_test_results = varied_crossover_test(file_name, 0.8)
  csv_name <- paste0('crossover_test_results','_',b,'.csv') #Write output csv file name
  write.csv(crossover_test_results, file = csv_name) #Write csv file
}

```
#Varying Both
```{r}

for(b in 1:6){
  if(b == 1){
    file_name = "knapsack_csv/knapPI_11_100_1000_2_900_3990_0.csv"
  }else if(b == 2){
    file_name = "knapsack_csv/knapPI_11_100_1000_84_25070_43824_0.csv"
  }else if(b == 3){
    file_name = "knapsack_csv/knapPI_11_100_1000_65_48518_46822_0.csv"
  }else if(b == 4){
    file_name = "knapsack_csv/knapPI_11_100_1000_40_23019_5808_0.csv"
  }else if(b == 5){
    file_name = "knapsack_csv/knapPI_11_100_1000_12_7719_8742_0.csv"
  }else if(b == 6){
    file_name = "knapsack_csv/knapPI_11_100_1000_97_46329_22872_0.csv"
  }
  mut_xover_test_results = varied_mutation_crossover_test(file_name) 
  csv_name <- paste0('mut_xover__test_results','_',b,'.csv') #Write output csv file name
  write.csv(mut_xover_test_results, file = csv_name) #Write csv file
}
```
#Varying Population

```{r}
for(b in 1:6){
  if(b == 1){
    file_name = "knapsack_csv/knapPI_11_100_1000_2_900_3990_0.csv"
  }else if(b == 2){
    file_name = "knapsack_csv/knapPI_11_100_1000_84_25070_43824_0.csv"
  }else if(b == 3){
    file_name = "knapsack_csv/knapPI_11_100_1000_65_48518_46822_0.csv"
  }else if(b == 4){
    file_name = "knapsack_csv/knapPI_11_100_1000_40_23019_5808_0.csv"
  }else if(b == 5){
    file_name = "knapsack_csv/knapPI_11_100_1000_12_7719_8742_0.csv"
  }else if(b == 6){
    file_name = "knapsack_csv/knapPI_11_100_1000_97_46329_22872_0.csv"
  }
  mut_xover_test_results = varied_population_test(file_name, .08, .51) 
  csv_name <- paste0('pop_test_results','_',b,'.csv') #Write output csv file name
  write.csv(mut_xover_test_results, file = csv_name) #Write csv file
}
```

#Custom Crossover Function Test

```{r}
for(b in 1:10){
  if(b == 1){
    file_name = "knapsack_csv/knapPI_11_100_1000_2_900_3990_0.csv"
  }else if(b == 2){
    file_name = "knapsack_csv/knapPI_11_100_1000_84_25070_43824_0.csv"
  }else if(b == 3){
    file_name = "knapsack_csv/knapPI_11_100_1000_65_48518_46822_0.csv"
  }else if(b == 4){
    file_name = "knapsack_csv/knapPI_11_100_1000_40_23019_5808_0.csv"
  }else if(b == 5){
    file_name = "knapsack_csv/knapPI_11_100_1000_12_7719_8742_0.csv"
  }else if(b == 6){
    file_name = "knapsack_csv/knapPI_11_100_1000_97_46329_22872_0.csv"
  }else if(b==7){
    file_name = "knapsack_csv/knapPI_11_100_1000_10_6239_10508_0.csv"
  }else if(b==8){
    file_name = "knapsack_csv/knapPI_11_100_1000_28_19591_12137_0.csv"
  }else if(b==9){
    file_name = "knapsack_csv/knapPI_11_100_1000_30_8510_33644_0.csv"
  }else if(b==10){
    file_name = "knapsack_csv/knapPI_11_100_1000_55_30369_25966_0.csv"
  }
  custom_crossover_test_results = modified_crossover_function_test(file_name, .08,.51, 135) 
  csv_name <- paste0('custom_crossover_test_results','_',b,'.csv') #Write output csv file name
  write.csv(custom_crossover_test_results, file = csv_name) #Write csv file
  rm(custom_crossover_test_results)
}
```

# Custom Mutation Function Test

```{r}
for(b in 1:10){
  if(b == 1){
    file_name = "knapsack_csv/knapPI_11_100_1000_2_900_3990_0.csv"
  }else if(b == 2){
    file_name = "knapsack_csv/knapPI_11_100_1000_84_25070_43824_0.csv"
  }else if(b == 3){
    file_name = "knapsack_csv/knapPI_11_100_1000_65_48518_46822_0.csv"
  }else if(b == 4){
    file_name = "knapsack_csv/knapPI_11_100_1000_40_23019_5808_0.csv"
  }else if(b == 5){
    file_name = "knapsack_csv/knapPI_11_100_1000_12_7719_8742_0.csv"
  }else if(b == 6){
    file_name = "knapsack_csv/knapPI_11_100_1000_97_46329_22872_0.csv"
  }else if(b==7){
    file_name = "knapsack_csv/knapPI_11_100_1000_10_6239_10508_0.csv"
  }else if(b==8){
    file_name = "knapsack_csv/knapPI_11_100_1000_28_19591_12137_0.csv"
  }else if(b==9){
    file_name = "knapsack_csv/knapPI_11_100_1000_30_8510_33644_0.csv"
  }else if(b==10){
    file_name = "knapsack_csv/knapPI_11_100_1000_55_30369_25966_0.csv"
  }
  custom_mutation_test_results = modified_mutate_function_test(file_name, .08,.51, 135) 
  csv_name <- paste0('custom_mutation_test_results','_',b,'.csv') #Write output csv file name
  write.csv(custom_mutation_test_results, file = csv_name) #Write csv file
  rm(custom_mutation_test_results)
}
```

# Baseline Test for Comparison

```{r}
for(b in 1:10){
  if(b == 1){
    file_name = "knapsack_csv/knapPI_11_100_1000_2_900_3990_0.csv"
  }else if(b == 2){
    file_name = "knapsack_csv/knapPI_11_100_1000_84_25070_43824_0.csv"
  }else if(b == 3){
    file_name = "knapsack_csv/knapPI_11_100_1000_65_48518_46822_0.csv"
  }else if(b == 4){
    file_name = "knapsack_csv/knapPI_11_100_1000_40_23019_5808_0.csv"
  }else if(b == 5){
    file_name = "knapsack_csv/knapPI_11_100_1000_12_7719_8742_0.csv"
  }else if(b == 6){
    file_name = "knapsack_csv/knapPI_11_100_1000_97_46329_22872_0.csv"
  }else if(b==7){
    file_name = "knapsack_csv/knapPI_11_100_1000_10_6239_10508_0.csv"
  }else if(b==8){
    file_name = "knapsack_csv/knapPI_11_100_1000_28_19591_12137_0.csv"
  }else if(b==9){
    file_name = "knapsack_csv/knapPI_11_100_1000_30_8510_33644_0.csv"
  }else if(b==10){
    file_name = "knapsack_csv/knapPI_11_100_1000_55_30369_25966_0.csv"
  }
  baseline_test_results = baseline_function_test(file_name, .08,.51, 135) 
  csv_name <- paste0('baseline_test_results','_',b,'.csv') #Write output csv file name
  write.csv(baseline_test_results, file = csv_name) #Write csv file
  rm(baseline_test_results)
}
```

# Randomized Selection Testing

```{r}
for(b in 1:6){
  if(b == 1){
    file_name = "knapsack_csv/knapPI_11_100_1000_2_900_3990_0.csv"
  }else if(b == 2){
    file_name = "knapsack_csv/knapPI_11_100_1000_84_25070_43824_0.csv"
  }else if(b == 3){
    file_name = "knapsack_csv/knapPI_11_100_1000_65_48518_46822_0.csv"
  }else if(b == 4){
    file_name = "knapsack_csv/knapPI_11_100_1000_40_23019_5808_0.csv"
  }else if(b == 5){
    file_name = "knapsack_csv/knapPI_11_100_1000_12_7719_8742_0.csv"
  }else if(b == 6){
    file_name = "knapsack_csv/knapPI_11_100_1000_97_46329_22872_0.csv"
  }
  pop_values = sample(50:250, 30, replace = TRUE)
  random_selection_comparison_test_results = random_selection_comparison_test(file_name, .08,.51, pop_values) 
  csv_name <- paste0('random_selection_comparison_test_results','_',b,'.csv') #Write output csv file name
  write.csv(random_selection_comparison_test_results, file = csv_name) #Write csv file
  rm(random_selection_comparison_test_results)
  random_selection_test_results = random_selection_test(file_name, .08,.51, pop_values) 
  csv_name <- paste0('random_selection_test_results','_',b,'.csv') #Write output csv file name
  write.csv(random_selection_test_results, file = csv_name) #Write csv file
  rm(random_selection_test_results)
}

```

#Random Solution Generation Vs. Baseline

```{r}
for(b in 1:6){
  baseline_name <- paste0('./a_baseline_output/baseline_test_results','_',b,'.csv')
  fitness_vals = as.vector(read.csv(baseline_name)['fitnessCalls'])
  if(b == 1){
    file_name = "knapsack_csv/knapPI_11_100_1000_2_900_3990_0.csv"
  }else if(b == 2){
    file_name = "knapsack_csv/knapPI_11_100_1000_84_25070_43824_0.csv"
  }else if(b == 3){
    file_name = "knapsack_csv/knapPI_11_100_1000_65_48518_46822_0.csv"
  }else if(b == 4){
    file_name = "knapsack_csv/knapPI_11_100_1000_40_23019_5808_0.csv"
  }else if(b == 5){
    file_name = "knapsack_csv/knapPI_11_100_1000_12_7719_8742_0.csv"
  }else if(b == 6){
    file_name = "knapsack_csv/knapPI_11_100_1000_97_46329_22872_0.csv"
  }
  print(paste0('b = ', b))
  all_in_one_test_results = all_in_one_test(file_name, .08,.51, fitness_vals)
  csv_name <- paste0('all_in_one_test_results','_',b,'.csv') #Write output csv file name
  write.csv(all_in_one_test_results, file = csv_name) #Write csv file
}

```

# Statistical Analysis 

```{r}
one_way_analysis_mutation("./a_mutation_output/mutation_test_results_1.csv",
                          "./a_mutation_output/mutation_test_results_2.csv",
                          "./a_mutation_output/mutation_test_results_3.csv",
                          "./a_mutation_output/mutation_test_results_4.csv",
                          "./a_mutation_output/mutation_test_results_5.csv",
                          "./a_mutation_output/mutation_test_results_6.csv")



```

```{r}
one_way_analysis_crossover("./a_crossover_output/crossover_test_results_1.csv",
                           "./a_crossover_output/crossover_test_results_2.csv",
                           "./a_crossover_output/crossover_test_results_3.csv",
                           "./a_crossover_output/crossover_test_results_4.csv",
                           "./a_crossover_output/crossover_test_results_5.csv",
                           "./a_crossover_output/crossover_test_results_6.csv")




```

```{r}
two_way_analysis_combination("./a_combined_output/mut_xover__test_results_1.csv",
                             "./a_combined_output/mut_xover__test_results_2.csv",
                             "./a_combined_output/mut_xover__test_results_3.csv",
                             "./a_combined_output/mut_xover__test_results_4.csv",
                             "./a_combined_output/mut_xover__test_results_5.csv",
                             "./a_combined_output/mut_xover__test_results_6.csv")


```

```{r}
new_mutation_xover("./a_baseline_output/baseline_test_results_1.csv",
                   "./a_baseline_output/baseline_test_results_2.csv",
                   "./a_baseline_output/baseline_test_results_3.csv",
                   "./a_baseline_output/baseline_test_results_4.csv",
                   "./a_baseline_output/baseline_test_results_5.csv",
                   "./a_baseline_output/baseline_test_results_6.csv",
                   "./a_baseline_output/baseline_test_results_7.csv",
                   "./a_baseline_output/baseline_test_results_8.csv",
                   "./a_baseline_output/baseline_test_results_9.csv",
                   "./a_baseline_output/baseline_test_results_10.csv",
                   "./a_custom_mutation_output/custom_mutation_test_results_1.csv",
                   "./a_custom_mutation_output/custom_mutation_test_results_2.csv",
                   "./a_custom_mutation_output/custom_mutation_test_results_3.csv",
                   "./a_custom_mutation_output/custom_mutation_test_results_4.csv",
                   "./a_custom_mutation_output/custom_mutation_test_results_5.csv",
                   "./a_custom_mutation_output/custom_mutation_test_results_6.csv",
                   "./a_custom_mutation_output/custom_mutation_test_results_7.csv",
                   "./a_custom_mutation_output/custom_mutation_test_results_8.csv",
                   "./a_custom_mutation_output/custom_mutation_test_results_9.csv",
                   "./a_custom_mutation_output/custom_mutation_test_results_10.csv",
                   "./a_custom_crossover_output/custom_crossover_test_results_1.csv",
                   "./a_custom_crossover_output/custom_crossover_test_results_2.csv",
                   "./a_custom_crossover_output/custom_crossover_test_results_3.csv",
                   "./a_custom_crossover_output/custom_crossover_test_results_4.csv",
                   "./a_custom_crossover_output/custom_crossover_test_results_5.csv",
                   "./a_custom_crossover_output/custom_crossover_test_results_6.csv",
                   "./a_custom_crossover_output/custom_crossover_test_results_7.csv",
                   "./a_custom_crossover_output/custom_crossover_test_results_8.csv",
                   "./a_custom_crossover_output/custom_crossover_test_results_9.csv",
                   "./a_custom_crossover_output/custom_crossover_test_results_10.csv")
                   
                   
  





```

```{r}
var_pop_size("./a_pop_output/pop_test_results_1.csv",
                   "./a_pop_output/pop_test_results_2.csv",
                   "./a_pop_output/pop_test_results_3.csv",
                   "./a_pop_output/pop_test_results_4.csv",
                   "./a_pop_output/pop_test_results_5.csv",
                   "./a_pop_output/pop_test_results_6.csv")

```


